/*
 * Logly lift.json API
 * Logly lift.json API for Lift Mobile SDK
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package jp.co.logly.Lift;

import jp.co.logly.ApiInvoker.ApiException;
import jp.co.logly.Lift.Result.InlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Liftレコメンデーション結果検索
     *
     * Liftレコメンデーション結果検索 注：返される結果数はLogly Lift コンソールの方で設定するが、表示はエリアの空きがある分だけ表示される
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestLiftTest() throws ApiException {
        Long adspotId = null;
        Long widgetId = null;
        String url = null;
        String ref = null;
        String toplevel = null;
        InlineResponse200 response = api.requestLift(adspotId, widgetId, url, ref, toplevel);

        // TODO: test validations
    }
    
}
